# -*- coding: utf-8 -*-'

# subset of cohesive markers
# list of sentence transitions by Eli Hinkel ("Matters of Cohesion in L2 Academic texts")
SENTENCE_TRANSITIONS = [
'above all',
'accordingly',
'additionally',
'after all',
'again',
'all in all',
'all the same',
'also',
'altogether',
'and so',
'and still',
'anyhow',
'anyway',
'anyways',
'as a consequence',
'as a matter of fact',
'as a result',
'as in consequence',
'at any rate',
'at last',
'at the same time',
'besides',
'better still',
'but then',
'but yet',
'by the same token',
'by the way',
'consequently',
'conversely',
'else',
'even worse',
'eventually',
'finally',
'first',
'first of all',
'firstly',
'for all that',
'for one thing',
'fourth',
'fourthly',
'furthermore',
'hence',
'however',
'in addition',
'in any case',
'in any event',
'in conclusion',
'in contrast',
'in fact',
'in sum',
'in the first place',
'in the meantime',
'in the meanwhile',
'in the same way',
'in the second place',
'in the third place',
'incidentally',
'lastly',
'likewise',
'meantime',
'meanwhile',
'moreover',
'nevertheless',
'next',
'nonetheless',
'now',
'on the contrary',
'on the other hand',
'once',
'one again',
'originally',
'otherwise',
'rather',
'second',
'second of all',
'secondly',
'similarly',
'somehow',
'still',
'subsequently',
'that said',
'then',
'then again',
'therefore',
'third',
'third of all',
'thirdly',
'though',
'thus',
'to begin with',
'to conclude',
'to start with',
'to sum up',
'to summarize',
'yet'
]